dist: trusty
sudo: false
language: cpp

addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    - g++-5
    - libsdl2-dev

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ../
  - cmake --build . --target YoAudio --config Debug
