dist: trusty
sudo: false
language: cpp

addons:
        sources:
                ubuntu-toolchain-r-test
        apt:
                g++-5
                libsdl2-dev

script:
        build_Linux_Make.sh
